"""Typed, immutable loader for the committed CAD parameter snapshot.

The snapshot (data/leg-params.json) is generated by `make params` from the OpenSCAD
sources and is the only source of CAD numbers for this package. See ADR-0005.
"""

import json
from dataclasses import dataclass
from importlib import resources
from pathlib import Path
from typing import Any

SCHEMA_VERSION = 1


class ParamsError(ValueError):
    """The snapshot is missing, malformed or has an unsupported schema."""


@dataclass(frozen=True)
class LegGeometry:
    tier: str
    coxa_l: float
    femur_l: float
    tibia_l: float
    leg_lane_dy: float
    cb_zmid: float
    tb_zax: float
    ft_r: float
    ft_floor: float
    knee_to_foot: float
    foot_dy: float


@dataclass(frozen=True)
class Limits:
    fit_alpha: tuple[float, ...]
    fit_phi: tuple[float, ...]


@dataclass(frozen=True)
class Servo:
    name: str
    provisional: bool
    range_deg: float
    pulse_us: tuple[float, ...]
    mass_kg: float
    stall_kgcm: tuple[tuple[float, float], ...]
    v_nom: float


@dataclass(frozen=True)
class Torque:
    supply_v: float
    n_servo: float
    link_g_per_mm: float
    m_body_kg: float
    k_dyn: float
    derate_static: float
    derate_peak: float


@dataclass(frozen=True)
class Params:
    leg: LegGeometry
    limits: Limits
    servo: Servo
    torque: Torque
    fk_golden: tuple[tuple[float, float, float, float, float], ...]
    provisional_names: tuple[str, ...]

    @property
    def provisional(self) -> bool:
        """True while any exported value is provisional (servo flag or a listed name)."""
        return self.servo.provisional or bool(self.provisional_names)


def _get(node: dict[str, Any], key: str, where: str) -> Any:
    if key not in node:
        raise ParamsError(f"missing key '{where}{key}'")
    return node[key]


def _section(root: dict[str, Any], key: str) -> dict[str, Any]:
    node = _get(root, key, "")
    if not isinstance(node, dict):
        raise ParamsError(f"'{key}' must be an object")
    return node


def _num(node: dict[str, Any], key: str, where: str) -> float:
    value = _get(node, key, where)
    if isinstance(value, bool) or not isinstance(value, int | float):
        raise ParamsError(f"'{where}{key}' must be a number, got {value!r}")
    return float(value)


def _nums(node: dict[str, Any], key: str, where: str) -> tuple[float, ...]:
    value = _get(node, key, where)
    if not isinstance(value, list) or not all(
        isinstance(v, int | float) and not isinstance(v, bool) for v in value
    ):
        raise ParamsError(f"'{where}{key}' must be a list of numbers")
    return tuple(float(v) for v in value)


def _text(node: dict[str, Any], key: str, where: str) -> str:
    value = _get(node, key, where)
    if not isinstance(value, str):
        raise ParamsError(f"'{where}{key}' must be a string")
    return value


def _parse(data: Any) -> Params:
    if not isinstance(data, dict):
        raise ParamsError("snapshot root must be an object")
    version = _get(data, "schema_version", "")
    if version != SCHEMA_VERSION:
        raise ParamsError(f"unsupported schema_version {version!r} (expected {SCHEMA_VERSION})")
    leg, lim, srv, tq = (_section(data, k) for k in ("leg", "limits", "servo", "torque"))
    names = _get(data, "provisional", "")
    if not isinstance(names, list) or not all(isinstance(n, str) for n in names):
        raise ParamsError("'provisional' must be a list of names")
    flag = _get(srv, "provisional", "servo.")
    if not isinstance(flag, bool):
        raise ParamsError("'servo.provisional' must be a boolean")
    stall = tuple(
        (float(row[0]), float(row[1]))
        for row in _get(srv, "stall_kgcm", "servo.")
        if len(row) == 2 and all(isinstance(v, int | float) for v in row)
    )
    golden = _get(data, "fk_golden", "")
    if not isinstance(golden, list) or not all(
        isinstance(r, list) and len(r) == 5 and all(isinstance(v, int | float) for v in r)
        for r in golden
    ):
        raise ParamsError("'fk_golden' must be a list of [alpha, phi, x, y, z] rows")
    return Params(
        leg=LegGeometry(
            tier=_text(leg, "tier", "leg."),
            **{
                k: _num(leg, k, "leg.")
                for k in (
                    "coxa_l femur_l tibia_l leg_lane_dy cb_zmid tb_zax ft_r ft_floor "
                    "knee_to_foot foot_dy"
                ).split()
            },
        ),
        limits=Limits(_nums(lim, "fit_alpha", "limits."), _nums(lim, "fit_phi", "limits.")),
        servo=Servo(
            name=_text(srv, "name", "servo."),
            provisional=flag,
            range_deg=_num(srv, "range_deg", "servo."),
            pulse_us=_nums(srv, "pulse_us", "servo."),
            mass_kg=_num(srv, "mass_kg", "servo."),
            stall_kgcm=stall,
            v_nom=_num(srv, "v_nom", "servo."),
        ),
        torque=Torque(
            **{
                k: _num(tq, k, "torque.")
                for k in (
                    "supply_v n_servo link_g_per_mm m_body_kg k_dyn derate_static derate_peak"
                ).split()
            }
        ),
        fk_golden=tuple((r[0], r[1], r[2], r[3], r[4]) for r in map(tuple, golden)),
        provisional_names=tuple(names),
    )


def load_params(path: Path | None = None) -> Params:
    """Load the snapshot at `path`, or the copy packaged with `hexapod` when omitted."""
    try:
        if path is None:
            text = resources.files("hexapod").joinpath("data/leg-params.json").read_text("utf-8")
        else:
            text = path.read_text("utf-8")
    except FileNotFoundError as exc:
        where = path or "hexapod/data/leg-params.json"
        raise ParamsError(f"params snapshot not found: {where}") from exc
    try:
        data = json.loads(text)
    except json.JSONDecodeError as exc:
        raise ParamsError(f"params snapshot is not valid JSON: {exc}") from exc
    return _parse(data)
